version: '2'

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    mysql:
        driver: local

    redis:
        driver: local

services:
    app:
        build: .
        environment:
            PHP_MEM_LIMIT: 512
            PHP_ERRORS_STDERR: 1
            REAL_IP_HEADER: 1
            HIDE_NGINX_HEADERS: 1
        links:
            - redis
        depends_on:
            - redis
            - mysql
        networks:
          - frontend
          - backend

    balancer:
        image: dockercloud/haproxy:latest
        ports:
            - 80:80
            - 1930:1936
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app
        networks:
            - frontend
            - backend

    redis:
        image: redis:alpine
        volumes:
            - ${DATA_PATH_HOST}/redis:/data
        networks:
            - frontend
            - backend

    worker:
        build:
            context: ./
            dockerfile: ./deploy/php-worker/Dockerfile
        volumes:
            - ./deploy/php-worker/supervisord.d:/etc/supervisord.d
        depends_on:
          - app
          - redis
          - mysql
        networks:
            - backend

    mysql:
        build:
            context: ./deploy/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        ports:
            - 3011:3306
        networks:
            - frontend
            - backend


